/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    copy: typeof import('./src/components/Location copy.vue')['default']
    FadeInOnScroll: typeof import('./src/components/FadeInOnScroll.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Impressie: typeof import('./src/components/Impressie.vue')['default']
    Location: typeof import('./src/components/Location.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
